SH_COMPILER_HOME := ../shCompiler

# Depending on which operating system you are installing on, change the respective install PATH
INSTALL_DIRECTORY_WINDOWS := "c:/program files/DocThis"
INSTALL_DIRECTORY_OTHER := "/usr/local/DocThis"
