/*
 * Copyright (C) 2011-2012 Shahbaz Youssefi <ShabbyX@gmail.com>
 *
 * This file is part of DocThis!.
 *
 * DocThis! is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * DocThis! is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with DocThis!.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "originals.h"

static string _css =
"/*********************************\n"
" ******** General Layout *********\n"
" *********************************/\n"
"body\n"
"{\n"
"\tbackground-color: #f4faff;\n"
"\tfont: 15px helvetica,arial,freesans,clean,sans-serif;\n"
"}\n"
"code\n"
"{\n"
"\tfont-size: 94%;\n"
"\tfont-family: Monaco,\"Courier New\",\"DejaVu Sans Mono\",\"Bitstream Vera Sans Mono\",monospace;\n"
"}\n"
"/* This is for the over all layout of the page, everything would be inside a div with this id */\n"
"#overall-layout\n"
"{\n"
"\twidth: 960px;\n"
"\tmargin: auto;\n"
"}\n"
"\t/*********************************\n"
"\t ******** Header & Bottom ********\n"
"\t *********************************/\n"
"\t/* The div responsible for the title, placed above the header */\n"
"\t#title\n"
"\t{\n"
"\t\twidth: 100%;\n"
"\t\ttext-align: center;\n"
"\t}\n"
"\t/* All the divs inside header would have this cless: */\n"
"\tdiv.header-bottom\n"
"\t{\n"
"\t\theight: 45px;\n"
"\t}\n"
"\t/* The div responsible for header/bottom. Previous page, next page and shortcuts go inside this */\n"
"\t#header\n"
"\t{\n"
"\t\twidth: 100%;\n"
"\t}\n"
"\t#bottom\n"
"\t{\n"
"\t\twidth: 100%;\n"
"\t}\n"
"\t/* The div responsible for previous page link */\n"
"\t#previous-page-header\n"
"\t{\n"
"\t\tfloat: left;\n"
"\t\twidth: 20%;\n"
"\t\ttext-align: left;\n"
"\t}\n"
"\t#previous-page-bottom\n"
"\t{\n"
"\t\tfloat: left;\n"
"\t\twidth: 20%;\n"
"\t\ttext-align: left;\n"
"\t}\n"
"\t/* The div responsible for next page link */\n"
"\t#next-page-header\n"
"\t{\n"
"\t\tfloat: left;\n"
"\t\twidth: 20%;\n"
"\t\ttext-align: right;\n"
"\t}\n"
"\t#next-page-bottom\n"
"\t{\n"
"\t\tfloat: left;\n"
"\t\twidth: 20%;\n"
"\t\ttext-align: right;\n"
"\t}\n"
"\t/* The div responsible for shortcut links */\n"
"\t#shortcuts-header\n"
"\t{\n"
"\t\tfloat: left;\n"
"\t\twidth: 60%;\n"
"\t\ttext-align: center;\n"
"\t}\n"
"\t#shortcuts-bottom\n"
"\t{\n"
"\t\tfloat: left;\n"
"\t\twidth: 60%;\n"
"\t\ttext-align: center;\n"
"\t}\n"
"\t/* The heading and subheading of the title */\n"
"\t#title-heading\n"
"\t{\n"
"\t\tmargin-bottom: 0px;\n"
"\t\tpadding-bottom: 0px;\n"
"\t}\n"
"\t#title-subheading\n"
"\t{\n"
"\t\tmargin-top: 0px;\n"
"\t\tpadding-top: 0px;\n"
"\t}\n"
"\t/* For that little text on the bottom that says the documentation was generated with DocThis! */\n"
"\t#docthis\n"
"\t{\n"
"\t\tcolor: #707070;\n"
"\t\tfont-size: 80%;\n"
"\t}\n"
"\ta.title\n"
"\t{\n"
"\t\ttext-decoration: none;\n"
"\t\tcolor: inherit;\n"
"\t}\n"
"\tcode.nextprev\n"
"\t{\n"
"\t\tfont-size: 100%;\n"
"\t\tfont-weight: bold;\n"
"\t}\n"
"/*********************************\n"
" ********** Normal Text **********\n"
" *********************************/\n"
"\tcode.inLink\n"
"\t{\n"
"\t\tfont-weight: bold;\n"
"\t}\n"
"\t/*********************************\n"
"\t ************ Heading ************\n"
"\t *********************************/\n"
"\tcode.inHeading\n"
"\t{\n"
"\t\tfont-weight: bold;\n"
"\t}\n"
"\t/*********************************\n"
"\t *********** Paragraph ***********\n"
"\t *********************************/\n"
"\tp\n"
"\t{\n"
"\t\ttext-align: justify;\n"
"\t\tpadding: 0px 15px 0px 15px;\n"
"\t}\n"
"\tp.indent\n"
"\t{\n"
"\t\ttext-align: justify;\n"
"\t\tpadding: 0px 15px 0px 45px;\n"
"\t}\n"
"\tcode.inline\n"
"\t{\n"
"\t\tbackground-color: #fcfcfc;\n"
"\t\tborder: 1px solid #dadada;\n"
"\t\tpadding: 0px 2px 0px;\n"
"\t\tborder-radius: 3px;\n"
"\t}\n"
"\t/*********************************\n"
"\t ************* Item **************\n"
"\t *********************************/\n"
"\tul\n"
"\t{\n"
"\t\tpadding-top: 10px;\n"
"\t\tpadding-bottom: 10px;\n"
"\t\ttext-align: justify;\n"
"\t}\n"
"\tol\n"
"\t{\n"
"\t\tpadding-top: 10px;\n"
"\t\tpadding-bottom: 10px;\n"
"\t\ttext-align: justify;\n"
"\t}\n"
"\tp.inListItem\n"
"\t{\n"
"\t\tmargin: inherit;\n"
"\t}\n"
"\tp.itemContinuation\n"
"\t{\n"
"\t\tmargin: inherit;\n"
"\t\tmargin-top: 5px;\n"
"\t}\n"
"\tp.itemContinuationWithIndent\n"
"\t{\n"
"\t\tmargin: inherit;\n"
"\t\tmargin-top: 5px;\n"
"\t\tpadding-left: 30px;\n"
"\t}\n"
"\t/*********************************\n"
"\t ************** Pre **************\n"
"\t *********************************/\n"
"\tpre\n"
"\t{\n"
"\t\tborder: 1px solid #cacaca;\n"
"\t\tpadding: 10px 15px 10px;\n"
"\t\tcolor: #000000;\n"
"\t\tbackground-color: #fcfcfc;\n"
"\t\toverflow:auto;\n"
"\t\tbackground-clip: padding-box;\n"
"\t\tborder-radius: 3px;\n"
"\t}\n"
"\tcode.pre\n"
"\t{\n"
"\t\tfont-size: 94%;\n"
"\t\tfont-family: Monaco,\"Courier New\",\"DejaVu Sans Mono\",\"Bitstream Vera Sans Mono\",monospace;\n"
"\t}\n"
"\ta.pre\n"
"\t{\n"
"\t\tcolor: inherit;\n"
"\t}\n"
"\ta.pre:hover\n"
"\t{\n"
"\t\tcolor: inherit;\n"
"\t}\n"
"\tspan.somewhatImportantCode\n"
"\t{\n"
"\t\tcolor: #222222;\n"
"\t\tfont-weight: bold;\n"
"\t}\n"
"\tspan.veryImportantCode\n"
"\t{\n"
"\t\tcolor: #004080;\n"
"\t\tfont-weight: bold;\n"
"\t}\n"
"div.hr\n"
"{\n"
"\theight: 0px;\n"
"\tmargin: 10px 0px;\n"
"\twidth: 100%;\n"
"\tbackground-color: #FFFFFF;\n"
"\tborder-top: 1px solid #444;\n"
"\tborder-bottom: 1px solid #aaa;\n"
"\tborder-left-style: none;\n"
"\tborder-right-style: none;\n"
"}\n"
"code.inSeeAlso\n"
"{\n"
"\tfont-weight: bold;\n"
"}\n"
"embed\n"
"{\n"
"\twidth: 100%;\n"
"\theight: 100%;\n"
"}\n"
"object\n"
"{\n"
"\twidth: 100%;\n"
"\theight: 100%;\n"
"}\n"
"/*********************************\n"
" ******* Code Explanation ********\n"
" *********************************/\n"
"\t/*********************************\n"
"\t ****** Summary of Elements ******\n"
"\t *********************************/\n"
"\tcode.overview\n"
"\t{\n"
"\t\tfont-weight: bold;\n"
"\t}\n"
"\tp.overview\n"
"\t{\n"
"\t\tpadding: 0px 0px 0px 30px;\n"
"\t\tmargin: 0px 0px 3px;\n"
"\t}\n"
"\ta.overview\n"
"\t{\n"
"\t\tfont-weight: bold;\n"
"\t}\n"
"\tp.shortDesc\n"
"\t{\n"
"\t\tpadding: 0px 0px 0px 60px;\n"
"\t\tmargin-top: 0px;\n"
"\t\tmargin-bottom: 5px;\n"
"\t}\n"
"\tp.groupShortDesc\n"
"\t{\n"
"\t\tpadding: 0px 0px 0px 30px;\n"
"\t\tmargin-top: 0px;\n"
"\t\tmargin-bottom: 10px;\n"
"\t}\n"
"\t/*********************************\n"
"\t ******* Explanation Body ********\n"
"\t *********************************/\n"
"\tdt\n"
"\t{\n"
"\t\tfont-size: 115%;\n"
"\t\tpadding: 0px 0px 0px 0px;\n"
"\t\ttext-align: justify;\n"
"\t}\n"
"\tdd\n"
"\t{\n"
"\t\tpadding: 0px 0px 0px 0px;\n"
"\t\tmargin: 0px 0px 0px 30px;\n"
"\t\ttext-align: justify;\n"
"\t}\n"
"\t\t/*********************************\n"
"\t\t *** Element's Full Definition ***\n"
"\t\t *********************************/\n"
"\t\tcode.def\n"
"\t\t{\n"
"\t\t\tfont-weight: bold;\n"
"\t\t}\n"
"\t\ttable.def\n"
"\t\t{\n"
"\t\t\tborder: 1px solid #868686;\n"
"\t\t\tbackground-color: #ffffff;\n"
"\t\t\tpadding: 10px 10px 10px 10px;\n"
"\t\t\tfont: inherit;\n"
"\t\t}\n"
"\t\ttd.def\n"
"\t\t{\n"
"\t\t\tpadding: 0px 0px 0px 0px;\n"
"\t\t\twhite-space:nowrap;\n"
"\t\t}\n"
"\t\ttd.defDefValue\n"
"\t\t{\n"
"\t\t\tpadding: 00px 0px 0px 10px;\n"
"\t\t\twidth: 100%;\n"
"\t\t}\n"
"\t\ttd.defLastColumn\n"
"\t\t{\n"
"\t\t\tpadding: 00px 0px 0px 0px;\n"
"\t\t\twidth: 100%;\n"
"\t\t}\n"
"\t\ttd.defRetValue\n"
"\t\t{\n"
"\t\t\tpadding: 0px 0px 0px 0px;\n"
"\t\t\twidth: 100%;\n"
"\t\t}\n"
"\t\t/*********************************\n"
"\t\t **** Element's Argument List ****\n"
"\t\t *********************************/\n"
"\t\tul.defInput\n"
"\t\t{\n"
"\t\t\tpadding-top: 0px;\n"
"\t\t\tpadding-bottom: 0px;\n"
"\t\t\ttext-align: justify;\n"
"\t\t}\n"
"\t\tcode.defInput\n"
"\t\t{\n"
"\t\t\tfont-size: 100%;\n"
"\t\t\tfont-weight: bold;\n"
"\t\t}\n"
"\t\tp.defInput\n"
"\t\t{\n"
"\t\t\tpadding: 0px;\n"
"\t\t\tmargin: 0px;\n"
"\t\t}\n"
"/*********************************\n"
" ********* Globals Page **********\n"
" *********************************/\n"
"h2.globals\n"
"{\n"
"\tmargin-top: 0px;\n"
"\tmargin-bottom: 0px;\n"
"\tpadding-top: 0px;\n"
"\tpadding-bottom: 5px;\n"
"}\n"
"h3.globals\n"
"{\n"
"\tmargin-top: 0px;\n"
"\tmargin-bottom: 0px;\n"
"\tpadding-top: 5px;\n"
"\tpadding-bottom: 5px;\n"
"\tpadding-left: 15px;\n"
"}\n"
"h4.globals\n"
"{\n"
"\tmargin-top: 0px;\n"
"\tmargin-bottom: 0px;\n"
"\tpadding-top: 5px;\n"
"\tpadding-bottom: 5px;\n"
"\tpadding-left: 15px;\n"
"}\n"
"ul.globals\n"
"{\n"
"\tmargin-top: 0px;\n"
"\tmargin-bottom: 0px;\n"
"\tpadding-top: 0px;\n"
"\tpadding-bottom: 0px;\n"
"\tpadding-left: 45px;\n"
"}\n"
"li.globals\n"
"{\n"
"\tmargin-top: 0px;\n"
"\tmargin-bottom: 0px;\n"
"\tpadding-top: 0px;\n"
"\tpadding-bottom: 0px;\n"
"}\n"
"code.globals\n"
"{\n"
"\tfont-size: 100%;\n"
"\tfont-weight: bold;\n"
"}\n"
"a.globals\n"
"{\n"
"\ttext-decoration: none;\n"
"\tcolor: #2050b0;\n"
"}\n"
"a.globals:hover\n"
"{\n"
"\ttext-decoration: underline;\n"
"\tcolor: #2050b0;\n"
"}\n"
"a.globalsHeading\n"
"{\n"
"\ttext-decoration: none;\n"
"\tcolor: #103080;\n"
"}\n"
"a.globalsHeading:hover\n"
"{\n"
"\ttext-decoration: underline;\n"
"\tcolor: #103080;\n"
"}\n"
"div.globalsHr\n"
"{\n"
"\theight: 0px;\n"
"\tmargin: 10px 0px;\n"
"\twidth: 50%;\n"
"\tbackground-color: #FFFFFF;\n"
"\tborder-top: 1px solid #444;\n"
"\tborder-bottom: 1px solid #aaa;\n"
"\tborder-left-style: none;\n"
"\tborder-right-style: none;\n"
"}\n";

string getCss()
{
	return _css;
}
