#ifndef SKIN_KERNEL_VERSION_H
#define SKIN_KERNEL_VERSION_H

#define SKINK_STRINGIFY_(x)	#x
#define SKINK_STRINGIFY(x)	SKINK_STRINGIFY_(x)
#define SKINK_VERSION_MAJOR	@SKINK_VERSION_MAJOR@
#define SKINK_VERSION_MINOR	@SKINK_VERSION_MINOR@
#define SKINK_VERSION_REVISION	@SKINK_VERSION_REVISION@
#define SKINK_VERSION_BUILD	@SKINK_VERSION_BUILD@
#define SKINK_VERSION		SKINK_STRINGIFY(SKINK_VERSION_MAJOR)"."\
				SKINK_STRINGIFY(SKINK_VERSION_MINOR)"."\
				SKINK_STRINGIFY(SKINK_VERSION_REVISION)"."\
				SKINK_STRINGIFY(SKINK_VERSION_BUILD)

#endif
