#ifndef SKIN_USER_CONFIG_H
#define SKIN_USER_CONFIG_H

#define SKIN_USER_ACQ_PRIORITY			@SKIN_USER_ACQ_PRIORITY@
#define SKIN_SERVICE_PRIORITY			@SKIN_SERVICE_USER_PRIORITY@
#define SKIN_MAX_SERVICES			@SKIN_SERVICE_MAX_SERVICES@
#define SKIN_MAX_THREAD_DELAY			@SKIN_THREAD_MAX_DELAY@
#define SKIN_TASK_STACK_SIZE			@SKIN_TASK_STACK_SIZE@
#define SKIN_DEBUG				@SKIN_DEBUG@

#endif
