#ifndef SKIN_KERNEL_CONFIG_H
#define SKIN_KERNEL_CONFIG_H

#ifdef __KERNEL__
# define SKINK_TICK_PERIOD			@SKINK_TICK_PERIOD@
# define SKINK_KERNEL_ACQ_PRIORITY		@SKINK_ACQ_PRIORITY@
# define SKINK_SERVICE_ACQ_PRIORITY		@SKINK_SERVICE_ACQ_PRIORITY@
# define SKINK_SERVICE_PRIORITY			@SKINK_SERVICE_KERNEL_PRIORITY@
# define SKINK_MAX_DEVICES			@SKINK_DEVICE_MAX_DEVICES@
# define SKINK_MAX_SERVICES			@SKINK_SERVICE_MAX_SERVICES@
# define SKINK_TASK_STACK_SIZE			@SKINK_TASK_STACK_SIZE@
# define SKINK_MAX_THREAD_DELAY			@SKINK_THREAD_MAX_DELAY@
#endif

#define SKINK_MAX_BUFFERS			@SKINK_MAX_BUFFERS@
#define SKINK_MAX_SENSOR_LAYERS			@SKINK_MAX_LAYERS@
#define SKINK_MAX_NAME_LENGTH			@SKINK_MAX_NAME_LENGTH@
#define SKINK_LARGE_SKIN			@SKINK_LARGE_SKIN@
#define SKINK_DEBUG				@SKINK_DEBUG@

#endif
